[package]
name = "projet-super-calculatrice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.8.0"
log = "0.4.21"
num-complex = "0.4.6"
serde = "1.0.203"
tokio = "1.38.0"
